Fix typo in python example code
The spacing on the line that `raises` was invalid python.  It produces the error 

```
  File "/home/dave/tmp/dev/python/main.py", line 18
    raise Exception("input too long")
                                     ^
IndentationError: unindent does not match any outer indentation level
```

This update fixes the indentation so that a reader can copy and paste the code.